stages:
  - lint
  - test
  - deploy

variables:
  PYTHON_IMAGE: python:3.11-slim
  VENV_DIR: .venv

# Lint stage
python:
  stage: lint
  image: $PYTHON_IMAGE
  before_script:
    - python -m venv $VENV_DIR
    - source $VENV_DIR/bin/activate
    - pip install --upgrade pip
    - pip install ruff
  script:
    - ruff check .
  artifacts:
    paths:
      - ruff.log
    when: always
  allow_failure: false

# Test stage
integration:
  stage: test
  image: $PYTHON_IMAGE
  before_script:
    - python -m venv $VENV_DIR
    - source $VENV_DIR/bin/activate
    - pip install --upgrade pip
    - pip install -r tests/requirements.txt
  script:
    - echo "TODO"
#    - cd tests
#    - pytest

# Deploy stage
deploy:
  stage: deploy
  image: alpine
  script:
    - echo "TODO"
  only:
    - main
  when: manual
