volumes:
  postgres_volume:
  redis_volume:
  prometheus_data:
  grafana_data:
  traefik_certificates:

services:
  webapp:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    depends_on:
      - solution
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`easydeploy.ru`)"
      - "traefik.http.routers.webapp.entrypoints=web"

  solution:
    environment:
      - CONFIG_PATH=.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
      - "8080:8080"
      - "2112:2112"
    volumes:
      - ./backend/logs:/app/logs
      - ./playbooks:/app/playbooks
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine3.17
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: ./backend
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
    depends_on:
      - pg

  runner:
    build:
      dockerfile: ./runner/Dockerfile
      context: ./
    ports:
      - "50051:50051"
    env_file:
      - runner/.env
    volumes:
      - ./playbooks:/app/playbooks
    depends_on:
      - solution
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes: 
      - redis_volume:/data
    env_file:
      - runner/.env

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp" # jaeger-client
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # web
      - "14268:14268"
      - "9411:9411"

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certificates:/certificates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.easydeploy.ru`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"